version: "2.2" # optional since v1.27.0
services:
  access:
    restart: always
    container_name: access
    env_file:
      - .env
    image: uwashl/access:latest
    ports:
      - "5000:3030"
  watchtower:
    restart: always
    env_file:
      - .env
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: access --interval 60 --cleanup

