const users = require('./users/users.service.js');
const trainings = require('./trainings/trainings.service.js');
const trainingItems = require('./training-items/training-items.service.js');
const completions = require('./completions/completions.service.js');
const contact = require('./contact/contact.service.js');
const feedback = require('./feedback/feedback.service.js');
const inductions = require('./inductions/inductions.service.js');
const inductionsPending = require('./inductions/pending/inductions-pending.service.js');
const reviews = require('./reviews/reviews.service.js');
const cards = require('./cards/cards.service.js');
const access = require('./access/access.service.js');
const notificationTemplates = require('./notification-templates/notification-templates.service.js');
const notifications = require('./notifications/notifications.service.js');
const notificationSchedules = require('./notification-schedules/notification-schedules.service.js');
const notificationsPreview = require('./notifications-preview/notifications-preview.service.js');
const homeLinks = require('./home-links/home-links.service.js');
const labelPrinters = require('./label-printers/label-printers.service.js');
const labels = require('./labels/labels.service.js');
const tokens = require('./tokens/tokens.service.js');
const tokenActions = require('./tokens/actions/tokens-actions.service.js');
const things = require('./things/things.service.js');
const thingsTags = require('./things/tags/tags.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(trainings);
  app.configure(trainingItems);
  app.configure(completions);
  app.configure(feedback);
  app.configure(contact);
  app.configure(inductions);
  app.configure(inductionsPending);
  app.configure(reviews);
  app.configure(cards);
  app.configure(access);
  app.configure(notificationTemplates);
  app.configure(notifications);
  app.configure(notificationSchedules);
  app.configure(notificationsPreview);
  app.configure(homeLinks);
  app.configure(labelPrinters);
  app.configure(labels);
  app.configure(tokens);
  app.configure(tokenActions);
  app.configure(things);
  app.configure(thingsTags);
};
