
module.exports = {
  type: {
    type: String,
    required: true,
    enum: [
      'image',
      'source',
      'manual',
      'datasheet',
      'sop',
      'risk-assessment',
      'certificate',
      'msds',
      'specification',
      'guide',
      'software',
      'hardware',
      'service',
      'warranty',
      'map',
      'other',
    ],
  },
  fileType: {
    type: String,
    required: true,
    enum: [
      'image',
      'document',
      'pdf',
      'video',
      'audio',
      'archive',
      'text',
      'markdown',
      'csv',
      'other',
    ],
  },
  provider: {
    type: String,
    required: true,
    enum: [
      'link',
      's3',
      'google-drive',
      'sharepoint',
      'fraser-image',
      'fraser-object',
      'youtube',
      'vimeo',
    ],
  },
  name: { type: String, required: true },
  description: { type: String },
  uri: { type: String },
  blurhash: { type: String },
};
